kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.12826163135538371
    roll: -0
    pitch: 0
    yaw: 3.6485295360362592e-05
  upper_arm:
    x: -0.00012817248942051195
    y: 0
    z: 0
    roll: 1.570778566652562
    pitch: 0
    yaw: -6.8921954986755907e-05
  forearm:
    x: -0.61250971897495043
    y: 0
    z: 0
    roll: 3.1331682138804751
    pitch: 3.1404425716944608
    yaw: -3.1414885617739952
  wrist_1:
    x: -0.57123524629367306
    y: 0.0024249054679267913
    z: 0.16386917348164856
    roll: 3.1267959200642648
    pitch: -3.1413339255335915
    yaw: -3.1415069041653916
  wrist_2:
    x: -4.0777623921028282e-06
    y: -0.11571000808563831
    z: 4.9643560701511688e-05
    roll: 1.5703672925352257
    pitch: 0
    yaw: -2.2411193142631242e-05
  wrist_3:
    x: -6.5672800423180296e-05
    y: 0.092230631630725091
    z: 1.3393856311136772e-05
    roll: 1.5709415481381765
    pitch: 3.1415926535897931
    yaw: 3.1415432505727598
  hash: calib_10221161915759351261