
sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_cloud
  image_topic: /camera/camera/aligned_depth_to_color/image_raw
  queue_size: 10
  near_clipping_plane_distance: 1.0
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 1.0
  padding_offset: 0.003
  max_update_rate: 10.0
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater

octomap_resolution: 0.01
